version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MONGODB_DATABASE: ${DATABASE_NAME}
    container_name: ${DATABASE_NAME}
    volumes:
      - ./mongo:/data/db
